version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - build
      - security
    reviewers:
      - hashicorp/terraform-core
    # only update HashiCorp actions, external actions managed by TSCCR
    allow:
      - dependency-name: hashicorp/*
      - dependency-name: hashicorp-dev/*
    groups:
    	github-actions-breaking:
        update-types:
          - major
    	github-actions-backward-compatible:
        update-types:
          - minor
          - patch
