sudo: false
language: go
go:
- 1.7
go_import_path: github.com/hashicorp/terraform
install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
script:
- make test vet
branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
