<<<<<<< HEAD
sudo: required

services:
  - docker

language: generic

# on branches: ignore multiple commits that will queue build jobs, just run latest commit
git:
  depth: 1
=======
dist: trusty
sudo: false
language: go
go:
- 1.8.1
>>>>>>> 0b2d02fc41b3ada007131e546797318ff049ef99

# establish environment variables
env:
  - TEST_DIR=examples/azure-encrypt-running-linux-vm

<<<<<<< HEAD
branches:
  only:
    # - master
    - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)
  - export EXISTING_IMAGE_URI=https://permanentstor.blob.core.windows.net/permanent-vhds/permanent-osdisk1.vhd
  - export EXISTING_STORAGE_ACCOUNT_NAME=permanentstor
  - export EXISTING_RESOURCE_GROUP=permanent
  - export KEY_VAULT_NAME=permanentkeyvault

# terraform deploy + script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./deploy.ci.sh
    on:
      repo: harijayms/terraform
      branch: topic-201-encrypt-running-linux-vm
=======
# Fetch consul for the backend and provider tests
before_install:
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip
  - mkdir ~/bin
  - mv consul ~/bin
  - export PATH="~/bin:$PATH"

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
script:
- make vet vendor-status test
- GOOS=windows go build
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.freenode.org#terraform-tool
    skip_join: true
    use_notice: true
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
>>>>>>> 0b2d02fc41b3ada007131e546797318ff049ef99
