sudo: required

services:
  - docker

language: generic

# on branches: ignore multiple commits that will queue build jobs, just run latest commit
git:
  depth: 1

# establish environment variables
env:
  - TEST_DIR=examples/azure-2-vms-loadbalancer-lbrules
branches:
  only:
  - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)

# terraform deploy script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./deploy.sh
    on:
      repo: 10thmagnitude/terraform
      branch: topic-201-2-vms-loadbalancer-lbrules

# cleanup
after_deploy: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./after_deploy.sh