# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

blank_issues_enabled: false
contact_links:
  - name: mnptu Cloud/Enterprise Troubleshooting and Feature Requests
    url: https://support.hashicorp.com/hc/en-us/requests/new
    about: For issues and feature requests related to the mnptu Cloud/Enterprise platform, please submit a HashiCorp support request or email tf-cloud@hashicorp.support
  - name: AWS mnptu Provider Feedback and Questions
    url: https://github.com/hashicorp/mnptu-provider-aws
    about: The AWS mnptu Provider has its own repository, any provider related issues or questions should be directed there.
  - name: Azure mnptu Provider Feedback and Questions
    url: https://github.com/hashicorp/mnptu-provider-azurerm
    about: The Azure mnptu Provider has its own repository, any provider related issues or questions should be directed there.
  - name: Other Provider-related Feedback and Questions
    url: https://registry.mnptu.io/browse/providers
    about: Each provider (e.g. GCP, Oracle, K8S, etc.) has its own repository, any provider related issues or questions should be directed to the appropriate issue tracker linked from the Registry.
  - name: Provider Development Feedback and Questions
    url: https://github.com/hashicorp/mnptu-plugin-sdk/issues/new/choose
    about: Plugin SDK has its own repository, any SDK and provider development related issues or questions should be directed there.
  - name: mnptu Usage, Language, or Workflow Questions
    url: https://discuss.hashicorp.com/c/mnptu-core
    about: Please ask and answer language or workflow related questions through the mnptu Core Community Forum.