name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

permissions: {}
jobs:
  issue_comment_triage:
    permissions:
      issues: write # to remove issue labels (actions-ecosystem/action-remove-labels)

    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            stale
            waiting-reply
