name: Set Release Mode

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'optionally set a prerelease string for the next targeted release version'
        required: false
        type: string

jobs:
  dev-mode:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Over-ride version pre-release
        if: "${{ github.event.inputs.prerelease != '' }}"
        environment:
          prerelease: "${{ github.event.inputs.prerelease }}"
        run:  |
          cd version
          sed -i "s/$/-$prerelease/g" 'VERSION'

      - name: get version
        id: get-product-version
        uses: hashicorp/actions-set-product-version@v1

      - name: Update changelog and add optional prerelease to version
        env:
          VERSION: "${{steps.get-product-version.outputs.product-version}}"
        run: |
          touch changelog.md_
          echo -e "## "${VERSION}" (Unreleased)\n" > "changelog.md_" &&
          cat CHANGELOG.md >> changelog.md_
          cp  CHANGELOG.md
          rm changelog.md_
          git add -A .
          git commit --allow-empty -a -m "Updating changelog (unreleased) and adding option prerelease field to version post release"
          git push origin "$(git rev-parse --abbrev-ref HEAD)"